schema_version: 1

context:
  version: "0.1.0"
  python_min: "3.10"

package:
  name: vmec-jax
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/v/vmec-jax/vmec_jax-${{ version }}.tar.gz
  sha256: 80d87356a57454575c9d72957795453b484c504ff4d8ca887d940785d99a8e2f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - vmec = vmec_jax.core.cli:main
      - vmec-jax = vmec_jax.core.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=68
    - pip
  run:
    - python >=${{ python_min }}
    - numpy
    - scipy
    - jax
    - netcdf4
    - matplotlib-base
    - booz-xform-jax >=0.1.1
    - solvax
    - packaging
    # python < 3.11
    - tomli

tests:
  - python:
      imports:
        - vmec_jax
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - vmec --help
      - vmec-jax --help

about:
  summary: JAX implementation of VMEC2000 with differentiable fixed-boundary and branch-local free-boundary research paths
  license: MIT
  license_file: LICENSE
  homepage: https://vmec-jax.readthedocs.io/
  repository: https://github.com/uwplasma/vmec_jax
  documentation: https://vmec-jax.readthedocs.io/

extra:
  recipe-maintainers:
    - rogeriojorge
    - matthewfeickert
